services:
    nginx: # ok
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./web/docker/nginx/nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./web/www:/var/www/html/
        ports:
            - 8080:80
        depends_on:
            - symfony
        networks:
            - net-for-front

    # php: # build ok
    #     # image: legrizzly/php-custom:3.0.2
    #     build:
    #         context: ./web/docker/php
    #         dockerfile: Dockerfile
    #     container_name: php
    #     volumes:
    #         - ./web/www:/var/www/html/
    #     networks:
    #         - net-for-front
    #         - net-for-back

    composer: # build ok
        # image: legrizzly/composer-custom:1.0.2
        build:
            context: ./web/docker/composer
            dockerfile: Dockerfile
        container_name: composer
        volumes:
            - ./web/www:/var/www
        # command: "--version"
        # command: ["require phpmailer/phpmailer"]

    symfony: # build ok
        # image: legrizzly/symfony-custom:1.0.2
        build:
            context: ./web/docker/symfony
            dockerfile: Dockerfile
        container_name: symfony
        volumes:
            - ./web/www:/var/www/html/
        networks:
            - net-for-front
            - net-for-back

networks:
    net-for-front:
        name: front-web
    net-for-back:
        name: back-db
# <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Dcoker Compose - Nginx, PHP, Postgres
#
#
#  #  Developed by    : legrizzly_0341
#  #  GitHub          : https://github.com/xalsie
#  #  Docker Hub      : https://hub.docker.com/u/legrizzly
#
# ██      ███████  ██████  ██████  ██ ███████ ███████ ██      ██    ██
# ██      ██      ██       ██   ██ ██    ███     ███  ██       ██  ██
# ██      █████   ██   ███ ██████  ██   ███     ███   ██        ████
# ██      ██      ██    ██ ██   ██ ██  ███     ███    ██         ██
# ███████ ███████  ██████  ██   ██ ██ ███████ ███████ ███████    ██
#
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_Update: 28/03/24_~~-->
